name: Upload iOS App to App Store

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 合并文件片段
    - name: Merge IPA parts
      run: |
        cat uploadtest/yooyo.ipa.part* > uploadtest/yooyo.ipa

    # 验证文件完整性
    - name: Verify file integrity
      run: |
        EXPECTED_MD5="9f613cb2f8730ed9889e8aff338bf115"
        ACTUAL_MD5=$(md5 -q uploadtest/yooyo.ipa)
        
        if [ "$EXPECTED_MD5" != "$ACTUAL_MD5" ]; then
          echo "IPA file integrity check failed"
          exit 1
        fi

    # 上传到 App Store
    - name: Upload to App Store using altool
      env:
        IPA_PATH: "uploadtest/yooyo.ipa"
        APPLE_ID: "sunzhiqing@lapininternationaltra.shop"
        APP_SPECIFIC_PASSWORD: "jxwl-pkbk-ttkj-orhe"
      run: |
        xcrun altool --upload-app -f "$IPA_PATH" \
          -t ios \
          -u "$APPLE_ID" \
          -p "$APP_SPECIFIC_PASSWORD" \
          --verbose

